[build]
target = "wasm32-unknown-unknown"

[target.wasm32-unknown-unknown]
rustflags = [
  "-C",
  "target-feature=+atomics,+bulk-memory,+mutable-globals",
  "-C",
  "link-arg=--import-memory",
  "-C",
  "link-arg=--shared-memory",
  "-C",
  "link-arg=--max-memory=1073741824",
  "-C",
  "link-arg=--export=os_boot",
  "-C",
  "link-arg=--export=os_suspend",
  "-C",
  "link-arg=--export=os_resume",
  "-C",
  "link-arg=--export=os_process_input",
  "-C",
  "link-arg=--export=os_get_render_tree",
  "-C",
  "link-arg=--export=os_collect_dirty_pages",
  "-C",
  "link-arg=--export=os_read_page",
  "-C",
  "link-arg=--export=os_write_page",
  "-C",
  "link-arg=--export=os_poll",
  "-C",
  "link-arg=--export=os_alloc",
  "-C",
  "link-arg=--export=os_free"
]
