[build]
target = "wasm32-unknown-unknown"

[target.wasm32-unknown-unknown]
rustflags = [
  "-C",
  "target-feature=+atomics,+bulk-memory,+mutable-globals",
  "-C",
  "link-arg=--import-memory",
  "-C",
  "link-arg=--shared-memory",
  "-C",
  "link-arg=--max-memory=1073741824",
  "-C",
  "link-arg=--export=kernel_boot",
  "-C",
  "link-arg=--export=kernel_poll",
  "-C",
  "link-arg=--export=kernel_mount_component"
]
