[build]
target = "wasm32-unknown-unknown"

[target.wasm32-unknown-unknown]
rustflags = [
  "-C",
  "target-feature=+atomics,+bulk-memory,+mutable-globals",
  "-C",
  "link-arg=--import-memory",
  "-C",
  "link-arg=--shared-memory",
  "-C",
  "link-arg=--max-memory=1073741824",
  "-C",
  "link-arg=--export=os_boot",
  "-C",
  "link-arg=--export=os_suspend",
  "-C",
  "link-arg=--export=os_resume",
  "-C",
  "link-arg=--export=os_process_input",
  "-C",
  "link-arg=--export=os_get_render_tree",
  "-C",
  "link-arg=--export=os_collect_dirty_pages",
  "-C",
  "link-arg=--export=os_compact_dirty",
  "-C",
  "link-arg=--export=os_read_page",
  "-C",
  "link-arg=--export=os_write_page",
  "-C",
  "link-arg=--export=os_load_component",
  "-C",
  "link-arg=--export=os_list_apps",
  "-C",
  "link-arg=--export=os_get_metrics",
  "-C",
  "link-arg=--export=os_terminal_snapshot",
  "-C",
  "link-arg=--export=os_editor_snapshot",
  "-C",
  "link-arg=--export=os_media_snapshot",
  "-C",
  "link-arg=--export=os_fs_explorer_snapshot",
  "-C",
  "link-arg=--export=activity_launch",
  "-C",
  "link-arg=--export=activity_terminate",
  "-C",
  "link-arg=--export=activity_send_intent",
  "-C",
  "link-arg=--export=window_create",
  "-C",
  "link-arg=--export=window_attach_buffer",
  "-C",
  "link-arg=--export=window_set_visuals",
  "-C",
  "link-arg=--export=fs_open",
  "-C",
  "link-arg=--export=fs_read_async",
  "-C",
  "link-arg=--export=fs_write_async",
  "-C",
  "link-arg=--export=media_stream_open",
  "-C",
  "link-arg=--export=media_push_pcm",
  "-C",
  "link-arg=--export=media_capture_frame",
  "-C",
  "link-arg=--export=hal_inject_sensor",
  "-C",
  "link-arg=--export=hal_inject_location",
  "-C",
  "link-arg=--export=hal_inject_audio_frame",
  "-C",
  "link-arg=--export=hal_inject_camera_frame",
  "-C",
  "link-arg=--export=hal_inject_peripheral_token",
  "-C",
  "link-arg=--export=hal_inject_nfc",
  "-C",
  "link-arg=--export=hal_inject_gamepad",
  "-C",
  "link-arg=--export=hal_inject_serial_read",
  "-C",
  "link-arg=--export=hal_inject_xr",
  "-C",
  "link-arg=--export=hal_set_haptics",
  "-C",
  "link-arg=--export=android_deploy_apk",
  "-C",
  "link-arg=--export=android_start_activity",
  "-C",
  "link-arg=--export=android_vm_tick",
  "-C",
  "link-arg=--export=os_poll",
  "-C",
  "link-arg=--export=os_alloc",
  "-C",
  "link-arg=--export=os_free"
]
